/**
 * Place-accurate cover/hero images for catalogue destinations.
 * Generated by scripts/buildPopularityCatalogue.mjs — do not edit by hand.
 */
export const PLACE_COVER_IMAGES: Record<string, string> = {
  'delhi': 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&q=80',
  'agra': 'https://images.unsplash.com/photo-1748433069400-3d7b4ac6b3e6?w=1200&q=80', // Taj Mahal — Agra only
  'jaipur': 'https://images.unsplash.com/photo-1650530777057-3a7dbc24bf6c?w=1200&q=80',
  'goa': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80', // coastal
  'mumbai': 'https://images.unsplash.com/photo-1598434192043-71111c1b3f41?w=1200&q=80',
  'varanasi': 'https://images.unsplash.com/photo-1561359313-0639aad49ca6?w=1200&q=80',
  'haridwar': 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=1200&q=80',
  'rishikesh': 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=1200&q=80',
  'manali': 'https://images.unsplash.com/photo-1482192505345-5655af888cc4?w=1200&q=80',
  'shimla': 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=1200&q=80',
  'udaipur': 'https://images.unsplash.com/photo-1703092289078-ff03b771237c?w=1200&q=80',
  'jodhpur': 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=1200&q=80',
  'jaisalmer': 'https://images.unsplash.com/photo-1471922694854-ff1b63b20054?w=1200&q=80',
  'amritsar': 'https://images.unsplash.com/photo-1623059508779-2542c6e83753?w=1200&q=80', // Golden Temple
  'bangalore': 'https://images.unsplash.com/photo-1697130383976-38f28c444292?w=1200&q=80',
  'mysore': 'https://images.unsplash.com/photo-1657856855186-7cf4909a4f78?w=1200&q=80',
  'ooty': 'https://images.unsplash.com/photo-1587538445896-d1f222cb0653?w=1200&q=80',
  'munnar': 'https://images.unsplash.com/photo-1633931698758-f59cdaf042a2?w=1200&q=80',
  'kochi': 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80',
  'alleppey': 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=1200&q=80',
  'darjeeling': 'https://images.unsplash.com/photo-1677858741767-1776b8dcde52?w=1200&q=80',
  'gangtok': 'https://images.unsplash.com/photo-1600242466690-c1c04f081762?w=1200&q=80',
  'nainital': 'https://images.unsplash.com/photo-1548266652-99cf27701ced?w=1200&q=80',
  'mussoorie': 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80',
  'leh': 'https://images.unsplash.com/photo-1619837374214-f5b9eb80876d?w=1200&q=80',
  'shirdi': 'https://images.unsplash.com/photo-1707733580929-19bf89c7ede6?w=1200&q=80',
  'tirupati': 'https://images.unsplash.com/photo-1741003412854-bd4b264c4af3?w=1200&q=80',
  'vaishno-devi': 'https://images.unsplash.com/photo-1691735214703-310c6594c6a8?w=1200&q=80',
  'bodh-gaya': 'https://images.unsplash.com/photo-1724303740927-bbb568013fd1?w=1200&q=80',
  'puri': 'https://images.unsplash.com/photo-1655394602738-eff266100405?w=1200&q=80', // coastal
  'khajuraho': 'https://images.unsplash.com/photo-1772457165831-d6df878706ef?w=1200&q=80',
  'hampi': 'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&q=80',
  'ajanta-ellora': 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=1200&q=80',
  'kolkata': 'https://images.unsplash.com/photo-1558431382-27e303142255?w=1200&q=80',
  'chennai': 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=80',
  'hyderabad': 'https://images.unsplash.com/photo-1696941515998-d83f24967aca?w=1200&q=80',
  'pondicherry': 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=1200&q=80', // coastal
  'kovalam': 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=80', // coastal
  'andaman': 'https://images.unsplash.com/photo-1586053226626-febc8817962f?w=1200&q=80', // coastal
  'mount-abu': 'https://images.unsplash.com/photo-1600356033695-a003690a6351?w=1200&q=80',
  'pushkar': 'https://images.unsplash.com/photo-1584245231969-b906af752fd3?w=1200&q=80',
  'dwarka': 'https://images.unsplash.com/photo-1711547979445-a72c87dfd004?w=1200&q=80',
  'rameswaram': 'https://images.unsplash.com/photo-1701665836329-57c6a17a2daf?w=1200&q=80',
  'madurai': 'https://images.unsplash.com/photo-1692173248120-59547c3d4653?w=1200&q=80',
  'coorg': 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
  'wayanad': 'https://images.unsplash.com/photo-1458668383970-8ddd3927deed?w=1200&q=80',
  'kodaikanal': 'https://images.unsplash.com/photo-1565315527461-d1d090885aed?w=1200&q=80',
  'mahabaleshwar': 'https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=1200&q=80',
  'rann-of-kutch': 'https://images.unsplash.com/photo-1670406312373-6d4d1776e4aa?w=1200&q=80',
  'ranthambore': 'https://images.unsplash.com/photo-1615551298862-0795063e3f1e?w=1200&q=80',
};

export function placeCover(id: string, fallback?: string): string {
  return PLACE_COVER_IMAGES[id] || fallback || PLACE_COVER_IMAGES.delhi;
}
